import { assert, assertEquals } from "jsr:@std/assert@1.0.13";
import { ATTRIBUTION_PATTERN, ATTRIBUTION_RECIPE, checkCommits, findAttribution } from "./source_standards.ts";
import { commitMessages } from "./git_commit_messages.ts";

Deno.test("findAttribution catches trailers, footers, and the robot, case-insensitively", () => {
  const text = [
    "fix(callout): reject expired tokens",
    "",
    "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>",
    "co-authored-by: GitHub Copilot <copilot@github.com>",
    "🤖 Generated with Claude Code",
    "Generated by Codex",
    "Co-authored-by: Jane Doe <jane@example.org>",
    "AI-assisted review of the plan (a sentence about AI, not attribution)",
  ].join("\n");
  assertEquals(findAttribution(text), [
    "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>",
    "co-authored-by: GitHub Copilot <copilot@github.com>",
    "🤖 Generated with Claude Code",
    "Generated by Codex",
  ]);
});

Deno.test("a human co-author and ordinary prose pass", () => {
  assertEquals(findAttribution("docs: explain the workbench\n\nCo-authored-by: Ola Nordmann <ola@example.no>\n"), []);
  assertEquals(findAttribution("The claude-ai skill directory is symlinked; generated files are marked DO NOT EDIT"), []);
});

Deno.test("checkCommits names the commit and line", () => {
  const sha = "0123456789abcdef0123456789abcdef01234567";
  const c = checkCommits([
    { sha, subject: "fix: tainted", message: "fix: tainted\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n" },
    { sha: "f".repeat(40), subject: "feat: clean", message: "feat: clean\n" },
  ]);
  assertEquals(c.clean, false);
  assertEquals(c.checked, 2);
  assertEquals(c.offending, [{ where: "0123456789ab fix: tainted", line: "Co-Authored-By: Claude <noreply@anthropic.com>" }]);
});

async function run(cwd: string, argv: string[], env: Record<string, string> = {}): Promise<{ code: number; out: string }> {
  const o = await new Deno.Command(argv[0], { args: argv.slice(1), cwd, env, stdout: "piped", stderr: "piped" }).output();
  return { code: o.code, out: new TextDecoder().decode(o.stdout) };
}

Deno.test("the model over git's data and the CI recipe agree on a real repository", async () => {
  const dir = await Deno.makeTempDir();
  try {
    const git = async (args: string[]) => {
      const r = await run(dir, ["git", "-c", "user.name=t", "-c", "user.email=t@example.org", "-c", "commit.gpgsign=false", ...args]);
      if (r.code !== 0) throw new Error(`git ${args.join(" ")} failed`);
      return r.out;
    };
    await git(["init", "-q", "-b", "main"]);
    await Deno.writeTextFile(`${dir}/a`, "1\n");
    await git(["add", "a"]);
    await git(["commit", "-q", "-m", "chore: base"]);
    await git(["checkout", "-q", "-b", "work"]);
    await Deno.writeTextFile(`${dir}/a`, "2\n");
    await git(["commit", "-q", "-am", "feat: clean commit\n\nA body with no attribution."]);
    await Deno.writeTextFile(`${dir}/a`, "3\n");
    await git(["commit", "-q", "-am", "fix: tainted\n\nCo-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>"]);

    const messages = await commitMessages(git, "main", "HEAD");
    const check = checkCommits(messages.commits);
    assertEquals(check.clean, false);
    assertEquals(check.offending.length, 1);
    const recipe = await run(dir, ["bash", "-c", ATTRIBUTION_RECIPE], { BASE: "main", HEAD: "HEAD" });
    assertEquals(recipe.code, 0, "recipe finds the hit");
    assertEquals(recipe.out.trim(), `${messages.commits[0].sha.slice(0, 12)} ${check.offending[0].line}`);

    await git(["commit", "-q", "--amend", "-m", "fix: reworded"]);
    assertEquals(checkCommits((await commitMessages(git, "main", "HEAD")).commits).clean, true);
    const recipeClean = await run(dir, ["bash", "-c", ATTRIBUTION_RECIPE], { BASE: "main", HEAD: "HEAD" });
    assertEquals(recipeClean.code, 1, "recipe prints nothing and exits 1 when clean");
    assertEquals(recipeClean.out, "");
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("CI carries the same pattern literally", async () => {
  const ci = await Deno.readTextFile(new URL("../../.forgejo/workflows/validate-attestation.yaml", import.meta.url));
  assert(ci.includes(`pattern='${ATTRIBUTION_PATTERN}'`), "validate-attestation.yaml must quote ATTRIBUTION_PATTERN verbatim");
});
